### ISSUE TITLE
Headers from multiple objects

### ISSUE THREAD

**Issue by ram-reddy** [mrodrig/json-2-csv#104]
## Background Information
- Module Version: `4.2.1 `
- Node/Browser Version: ` `

The issue I'm reporting is with:
- [x] json2csv
- [ ] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
when i provide an array like 
```json
[{"a":{"b":2,"c":"3"}}, 
{"a":{"c":3,"d":4}}]
```
output should be 
```csv
a.b, a.c, a.d
2,3,
,3,4
```
## Actual Behavior
```csv
a.b, a.c
2 ,3
,3
```
few headers are missing (un even json)
## Data Sample 
 

JSON:
```json
[{"a":{"b":2,"c":"3"}}, 
{"a":{"c":3,"d":4}}]
```

## Code Example
using the node version 

json2csv -F -i input.json -o out.csv

**Comment by mrodrig** [comment]
Hi @ram-reddy. Thanks for letting me know about that. Unfortunately, I think you might be looking for the other json to csv converter (`json2csv`) though since this module isn't yet on v4.2.1 (currently 3.2.0). Here's a link to that repo: https://github.com/zemirco/json2csv

For reference, I tested that example with this module and it provides the following output:
```csv
a.b,a.c,a.d
2,3,undefined
undefined,3,4
```

That makes me realize that I should probably add in an empty field value option for CLI usage. Spun that off into a separate issue (#105).

I'm going to close this out, but please feel free to re-open it if you decide to switch to this module (`json-2-csv`) and run into any issues. Thanks!
