### ISSUE TITLE
Read .csv file, and convert it to csv string for the csv2json

### ISSUE THREAD

**Issue by Mike-Van** [mrodrig/json-2-csv#108]
Hello, currently i have a .csv file, and i want to import and read it as string before passing it as argument to csv2json function. Can anyone suggest a quick and easy way to do this? I've been reading some stackoverflow questions online, but it seems too complicated.

**Comment by mrodrig** [comment]
Hi @Mike-Van.  Okay, that makes sense. It looks like you should be able to use the built in `fs` module to read the CSV file that you have so that you can get the file contents as a string before passing it to the csv2json function.  Here's a quick example of how to get it working with the `readFile` function in the `fs` module:

_open.js_
```javascript
let fs = require('fs'),
    converter = require('json-2-csv');

fs.readFile('./test.csv', function (err, data) {
  if (err) {
    return console.error('An error occurred while reading the file.', err);
  }

  let csv = data.toString();
  converter.csv2json(csv, function (err, json) {
    if (err) {
      return console.error('An error occurred during the CSV to JSON conversion', err);
    }

    console.log('JSON Objects: ', json);
  });
});
```

_test.csv_
```csv
let fs = require('fs'),
author,modules
mrodrig,"[""json-2-csv""]"
jsmith,[]
anonymous_user_123,"[""some_module"",""another_module"",""this other cool module""]"
```

_console output when run via `node open.js`_
```
JSON Objects:  [ { author: 'mrodrig', modules: [ 'json-2-csv' ] },
  { author: 'jsmith', modules: [] },
  { author: 'anonymous_user_123',
    modules:
     [ 'some_module', 'another_module', 'this other cool module' ] } ]
```

I believe that should answer your question, but please feel free to comment back if not.

Thanks!

**Comment by Mike-Van** [comment]
yes. This does help me out. Thanks. Now i got the data out of the CSV file. But its not structured correctly. 

Here's the sameple CSV file: 

```
No.,Company Name,Group,Priority,Survey,Sector,Name,JOB TITLE,Email,Mobile,Email Presentation,Presentation,Beta Sent ,Beta Participation,Beta Signed,# of outlets,Delivery Service,# delivery points,E-commerce,Turnover ($m),Size,Incharge Name ,Activity ,Contact Person ,Last Meeting ,Address,Address ( District),Address (City ),Notes,Website
1,Kyoudai Restaurant and Cafe ,,,,FOOD & BEVERAGE,Mr.Sothi,,sothitri2008@gmail.com,+855 10 730 606,Yes ,Yes,,,,1,,,,,S,Rachana,Meeting ,Mr.Sothi,2/27/19,,Khan Sen Sok,Phnom Penh,Called 26-Feb-19 got meeting with Mr.Sothy 27-Feb-19 He interested and he will contact soon. Now using PiPay and Darapay but no discount.,https://www.facebook.com/pg/KyoudaiRestaurantandCafe/about/?ref=page_internal
```
and here'is the output i got: 
```
{
        "\ufeffNo": {
            "": 1
        },
        "Company Name": "Kyoudai Restaurant and Cafe ",
        "Group": "",
        "Priority": "",
        "Survey": "",
        "Sector": "FOOD & BEVERAGE",
        "Name": "Mr.Sothi",
        "JOB TITLE": "",
        "Email": "sothitri2008@gmail.com",
        "Mobile": "+855 10 730 606",
        "Email Presentation": "Yes ",
        "Presentation": "Yes",
        "Beta Sent ": "",
        "Beta Participation": "",
        "Beta Signed": "",
        "# of outlets": 1,
        "Delivery Service": "",
        "# delivery points": "",
        "E-commerce": "",
        "Turnover ($m)": "",
        "Size": "S",
        "Incharge Name ": "Rachana",
        "Activity ": "Meeting ",
        "Contact Person ": "Mr.Sothi",
        "Last Meeting ": "2/27/19",
        "Address": "",
        "Address ( District)": "Khan Sen Sok",
        "Address (City )": "Phnom Penh",
        "Notes": "Called 26-Feb-19 got meeting with Mr.Sothy 27-Feb-19 He interested and he will contact soon. Now using PiPay and Darapay but no discount.",
        "Website\r": "https://www.facebook.com/pg/KyoudaiRestaurantandCafe/about/?ref=page_internal\r"
}
```
the first object in this should be `"No": 1` and last one should be without the `\r` character. can you tell me how i can fix this? Im trying to use this for serverless application. 

Here's my current code:
```
let converter = require('json-2-csv')
let fs = require('fs')

exports.handler = async (event, context) => {
  const file = fs.readFileSync('./Import/rachna.csv');

  const csv = file.toString();

  const allData = await converter.csv2jsonAsync(csv);

  const filtered = allData.filter(i => i["Company Name"] && i["Company Name"].length && i["\ufeffNo"][""] === 1)  

  return {
		statusCode: 200,
		body: JSON.stringify(filtered)
	}
}
```

**Comment by mrodrig** [comment]
Hi @Mike-Van. Glad to hear that seems to have worked! I'm not sure where your last comment went (I saw the email, but it's not showing up here for some reason). It looks like in the case you just need to set two options in order for the CSV to be converted properly to JSON.

First, the `\ufeff` character that you're seeing at the beginning, that's an Excel BOM (Byte Order Mark). The `excelBOM` option should take care of stripping that for you.

Also, the `\r` that is getting captured in the last field of each document is likely because your CSV is using `\r\n` end of line characters (the module by default looks for Linux line endings `\n`). If you set the `delimiter.eol` option to `'\r\n'` that should take care of it.

Your example code should look something like this with those options:
```
  const options = {
    delimiter: {
      eol: '\r\n'
    },
    excelBOM: true
  };

  const allData = await converter.csv2jsonAsync(csv, options);
```

Once those options are set, you should see the expected JSON results. Hopefully this helps!
