### ISSUE TITLE
Expand Array Objects via CLI

### ISSUE THREAD

**Issue by markwynter** [mrodrig/json-2-csv#121]
## Background Information
- Module Version: 3.5.3
- Node v.6.6

The issue I'm reporting is with:
 json2csv

Hi Mike

I've edited constants.json and set expandArrayObjects=true.

The CLI command I'm calling is:
json2csv asana.json -o asana.csv

The input JSON and output CSV files are attached.
[Archive.zip](https://github.com/mrodrig/json-2-csv/files/3219280/Archive.zip)

Is there anything obvious that I'm doing wrong?

Kind regards
Mark

**Comment by mrodrig** [comment]
Hi Mark,

Thanks for reporting that. I'm not sure why changing the constants.json file didn't work since it pulls the defaults from there, but regardless - good find that there wasn't a CLI option for that. I must have forgot to add it when I added the `expandArrayObjects` option. I apologize for that. I just added it and tested it with some local JSON files and it's working with that option specified now. I'm going to push this up in a few minutes and will get this fix published to NPM tonight in `3.5.4`. The new CLI option will be `-A` to specify `expandArrayObjects` should be `true`.

Thanks again for reporting this! Please feel free to let me know if you find anything else that isn't working as expected.

Best,
Mike

**Comment by mrodrig** [comment]
Published to NPM. Thanks again!

**Comment by markwynter** [comment]
Thanks Mike - much appreciated for your hard work and responsiveness - I upgraded to latest version, but I'm still having trouble producing the desired output using the "asana.json" input file contained in Archive.zip attached to my original message. The attached file "desired_csv.txt" is the output I'm hoping to produce?  Is this possible?
[desired_csv.txt](https://github.com/mrodrig/json-2-csv/files/3220050/desired_csv.txt)

**Comment by mrodrig** [comment]
Hi Mark - sorry that it still isn't behaving as you expect. I'm going to take a closer look to see what's causing it to output the data in an array instead of as individual rows. In the mean time, I'm going to re-open the issue. I'll let you know what I find and a rough timeline estimate once I have a chance to take a closer look.  Thanks!

**Comment by mrodrig** [comment]
Hi Mark,

Sorry for the delayed response. I've been looking through at how this gets handled in the module and at how other modules handle this particular scenario. While I definitely see the use case and found one other module that provides this behavior ([jsonexport](https://www.npmjs.com/package/jsonexport)), I'm not really sure that it's the behavior that I would expect based on the JSON. Since the `data` field is inside an object, I wouldn't expect the CSV to break out different items inside the data array to their own lines. That behavior just doesn't seem quite right since they aren't in fact top-level objects that are being converted. In my opinion, the best way to get the desired result based on the expected behavior would be to map the items in the data array to include any of the properties that you want, such as `next_page` and then pass the list in to `json2csv(...)` like this:

```javascript
let json2csv = require('json-2-csv'),
    _ = require('underscore'),

  data = {
     "data":[
        {
           "id":1122447119237433,
           "gid":"1122447119237433",
           "created_at":"2019-05-09T17:02:23.718Z",
           "followers":[
              {
                 "id":1121767743328353,
                 "gid":"1121767743328353",
                 "resource_type":"user"
              }
           ],
           "modified_at":"2019-05-09T17:02:35.864Z",
           "name":"Making feature image",
           "notes":"",
           "workspace":{
              "id":1121769302732055,
              "gid":"1121769302732055",
              "resource_type":"workspace"
           }
        },
        ...
     ],
     "next_page":null
  };

let mappedData = _.map(data.data, function (dataObj) {
  // Copy over next_page property to each object in data.data
  dataObj.next_page = data.next_page;
  return dataObj;
})

json2csv.json2csv(mappedData, function(err, csv){
    if(err) return console.log(err);
    console.log(csv);
}, { expandArrayObjects: true });
```

That produces the following CSV:

```csv
id,gid,created_at,followers.id,followers.gid,followers.resource_type,modified_at,name,notes,workspace.id,workspace.gid,workspace.resource_type,next_page
1122447119237433,1122447119237433,2019-05-09T17:02:23.718Z,1121767743328353,1121767743328353,user,2019-05-09T17:02:35.864Z,Making feature image,,1121769302732055,1121769302732055,workspace,null
1122447119237429,1122447119237429,2019-05-09T15:41:20.191Z,1121767743328353,1121767743328353,user,2019-05-09T17:02:00.596Z,Sharing on SM,,1121769302732055,1121769302732055,workspace,null
1122447119237427,1122447119237427,2019-05-09T15:40:07.485Z,1121767743328353,1121767743328353,user,2019-05-09T17:01:52.167Z,Adding Banners,,1121769302732055,1121769302732055,workspace,null
1122447119237425,1122447119237425,2019-05-09T15:39:47.540Z,1121767743328353,1121767743328353,user,2019-05-09T17:01:38.550Z,Uploading blog to WP,,1121769302732055,1121769302732055,workspace,null
1122447119237423,1122447119237423,2019-05-09T15:26:43.741Z,1121767743328353,1121767743328353,user,2019-05-09T15:27:28.190Z,Making post,,1121769302732055,1121769302732055,workspace,null
1122447119237421,1122447119237421,2019-05-09T15:26:38.072Z,1121767743328353,1121767743328353,user,2019-05-09T15:27:25.499Z,Preparing images,,1121769302732055,1121769302732055,workspace,null
1122447119237419,1122447119237419,2019-05-09T15:26:31.578Z,1121767743328353,1121767743328353,user,2019-05-09T17:28:16.415Z,Testing,,1121769302732055,1121769302732055,workspace,null
1122447119237417,1122447119237417,2019-05-09T15:26:22.044Z,1121767743328353,1121767743328353,user,2019-05-09T17:28:11.714Z,Exporting with API,,1121769302732055,1121769302732055,workspace,null
1122447119237415,1122447119237415,2019-05-09T15:26:03.604Z,1121767743328353,1121767743328353,user,2019-05-09T17:28:05.007Z,SEO,,1121769302732055,1121769302732055,workspace,null
1121817463440542,1121817463440542,2019-05-07T15:08:33.889Z,1121767743328353,1121767743328353,user,2019-05-07T15:11:52.391Z,Preparing blog post ideas,"Researching multiple apps for blog post

",1121769302732055,1121769302732055,workspace,null
```

I wish I could help more, but I honestly feel like the results you're seeing are what one would expect based on the JSON being passed in.

Please let me know if you have any other questions or if there's anything else that I can help out with.

**Comment by mrodrig** [comment]
This was brought up again in #124 so I'm taking another look.
