### ISSUE TITLE
Number-like values beginning with zero not quote escaped

### ISSUE THREAD

**Issue by josh-hemphill** [mrodrig/json-2-csv#128]
## Background Information
- Module Version: `3.5.5`
- Node/Browser Version: `Node 12.7.0`

The issue I'm reporting is with:
- [x] json2csv
- [ ] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

This might be more of a feature request.

Perhaps just as a behavior of the excelBOM option since it suggests use with excel.
Since using with excel, all number-like values that begin with 0 will get converted to a number.

## Data Sample 
JSON:
```json
[
{"numberLikeCodes":"00007", "otherText":"some other text"},
{"numberLikeCodes":"00005", "otherText":"some other text"}
]
```

## Code Example
```javascript
let options = {
	keys: [...columns],
	excelBOM: true,
	delimiter: {
		wrap: '"'
	}
}
```

**Comment by mrodrig** [comment]
Hi @josh-hemphill. Thanks for reporting this. I just tested this out on my Mac and it looks like with and without quotes, Excel ends up stripping the extra 0's and the cell is still marked as containing the "General" type. Maybe Excel on Windows behaves differently and converts the values to the "Number" type?

I'll try it out on my Windows machine later to see, but this definitely seems like a useful feature since it could be painful to manually set the appropriate types in Excel.

**Comment by mrodrig** [comment]
Sorry for the long delay in getting back to you. I took a look at this with Excel on my Windows machine and it looks like Excel's 'General' cell data type is what causes the zeroes to be hidden. If you go into the 'Format Cells' menu and change the type to 'Custom' then it will show the leading zeroes when the value is quoted. Since I can't specify the data type in advance in the CSV as far as I'm aware, I think the best option here is to format that cell's data type so it displays the actual cell value.

![image](https://user-images.githubusercontent.com/2199972/74496811-d3ea2b00-4ea9-11ea-8746-6c76eb6bda2f.png)

I checked again on my Mac and it looks like the 'Custom' cell data type also preserves the leading zeroes.
