### ISSUE TITLE
How do I give the keys a custom title?

### ISSUE THREAD

**Issue by smammadov1994** [mrodrig/json-2-csv#171]
Hello, I am using json-2-csv and I do not see in the documentation where I can give my own custom column headers? Right now it is using the keys as the column headers and when I change the keys to something else it fails to grab the data. How do I properly do this?

**Comment by mrodrig** [comment]
Hi @smammadov1994. Good question. There wasn't a way to specify a custom column title, but it's definitely a reasonable use case so I added that functionality in `3.8.0` which should be up on NPM now. You should be able to specify something like the following in order to set a custom column title for a specific key:

```json
const options = {
    keys: [
        {
            key: 'key1',
            title: 'Key 1' // This value will be used for the column title instead of 'key1' in the CSV output.
        },
        {
            key: 'key2' // An Object can be provided without a custom title as well.
        },
        'key3', // If no custom title is needed, a String can be provided instead.
        ...
    ]
}
```

Which would generate something like this:
```
Key 1,key2,key3
a1,a2,a3
b2,b2,b3
...
```

Hope this helps.
