### ISSUE TITLE
Can't be use with a stringify object but only with object that fields are strings

### ISSUE THREAD

**Issue by Franck-El** [mrodrig/json-2-csv#201]
## Background Information
- Module Version: ` 3.14.1`
- Node/Browser Version: ` 14.17.0`

The issue I'm reporting is with:
- [x ] json2csv
- [ ] csv2json

I have...
- [x ] searched to see if an issue has already been reported.
- [x ] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x ] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Code Example
```javascript
// Please include a simple example to replicate the issue
let converter = require('json-2-csv');
const obj1 = {
  a = 2,
  b = 'something'
};

const obj2 = {
  a = 5,
  b = 'other'
};

const arrOfObj = [obj1, obj2];
const str = JSON.stringify(arrOfObj);

converter.json2csvAsync(str).then(
        (csv) => fs.writeFile('data.csv', csv, (err) => {
            if (err)  throw err;
            console.log("data.csv is saved.");
        })
    ).catch((err) => console.log('ERROR: ' + err.message));

```

## Expected Behavior
Use json-2-csv on a stringify element to save it as a csv. (Not really an issue because it works well already, it's a suggestion for an update but I don't know where I can send it to you)

## Actual Behavior
Whereas using the simple stringify function, I need to do like this
```
arrOfObj.map(obj => {
    for (const prop in obj) {
        obj[prop] = `${obj[prop]}`;
    }
});
```

**Comment by mrodrig** [comment]
Thanks for reporting this @Franck-El. It's a good suggestion, though I'm not sure I want to add the logic in. My thought is that if someone were to pass a `String` in, then I could assume it's a JSON representation, but that assumption might be wrong and it could cause some confusion. It seems like passing an array of objects, or a single object, is probably better since this library is less likely to know of any peculiarities with regards to the data being passed that might affect the parsing.
