### ISSUE TITLE
Private Vulnerability Disclosure

### ISSUE THREAD

**Issue by scovetta** [mrodrig/json-2-csv#224]
Hello!
I've sent a few e-mails to since early August about a vulnerability we found in json-2-csv, but I'm not sure they're getting through. As part of our analysis through the OpenSSF [Alpha-Omega](https://openssf.org/community/alpha-omega) project, we scan and review important open source components, and then offer to work with maintainers on a fix.

We'd like to report this vulnerability privately to you -- do you have an approach that you'd prefer we follow?

**Comment by mrodrig** [comment]
Hi Michael. Apologies for the delay - I'm not sure why but I never saw your emails in my inbox, however, after searching for your name, I was able to find the emails. I've been looking into the potential issue you described and will follow up by email within the next day since I cannot replicate the unhandled error causing a process crash scenario given it's captured within a promise chain and passed to the next registered `catch` block. Thanks for reaching out again to ensure I was notified.
