### ISSUE TITLE
csv2json Allow CSV Files Without Headers

### ISSUE THREAD

**Issue by mgrist** [mrodrig/json-2-csv#227]
It would be awesome if this library had an option for csv2json that allowed for csv files with no headers. Maybe by allowing to specify headers.

**Comment by mrodrig** [comment]
Thanks for reporting that @mgrist. I've typically just recommended appending a header to the CSV prior to passing it to `csv2json` in the past, but I could definitely see this being useful, especially if you're really only interested in some of the columns. I'll take a look at how I might be able to implement this and will get back to you with an update.

**Comment by mrodrig** [comment]
Hi @mgrist. Thanks again for reporting this. I ended up implementing this using a new `headerFields` option for csv2json since there wasn't a great way to implement it using the existing `keys` option without breaking other possible use cases. With the new option, an array of strings can be specified in place of the first row containing the field names, meaning all of the rows will be parsed as records, rather than skipping the first line. The README is updated with some more info and it's published in `3.19.0` on NPM now. Let me know if you have any questions or have any other thoughts on how to improve it.  Thanks again!

**Comment by mgrist** [comment]
@mrodrig That is awesome. Great job you got it implemented quickly! I needed to parse a CSV file in an S3 bucket but could not add a header column or modify it because other programs rely on it to be a specific format. This will be super useful. Thanks! 🤙
