### ISSUE TITLE
prependHeader: false, is not working

### ISSUE THREAD

**Issue by subinpaulneo** [mrodrig/json-2-csv#232]
## Background Information
- Module Version: `"^3.20.0" `
- Node/Browser Version: ` `

The issue I'm reporting is with:
- [ x] json2csv
- [ ] csv2json

I have...
- [x ] searched to see if an issue has already been reported.
- [ x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x ] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
prependHeader: false should not generate csv with header

## Actual Behavior
prependHeader: false is adding header as first row

## Data Sample 
CSV:
```csv
productID,sku,customFields
2184,9789702636977,"[{""id"":9812,""name"":""Edition"",""value"":""1""},{""id"":9813,""name"":""Publisher"",""value"":""Pearson ELL""},{""id"":9814,""name"":""Copyright"",""value"":""2018""},{""id"":9815,""name"":""Authors"",""value"":""Antonia Clare, Frances Eales, JJ Wilson, Steve Oakes""},{""id"":9816,""name"":""Shipping required"",""value"":""NO""},{""id"":9817,""name"":""Subscription Length"",""value"":""12 Months""},{""id"":13491,""name"":""Format"",""value"":""Digital""}]"
productID,sku,customFields
2185,9789702636939,"[{""id"":9818,""name"":""Format"",""value"":""Digital""},{""id"":9819,""name"":""Edition"",""value"":""1""},{""id"":9820,""name"":""Publisher"",""value"":""Pearson ELL""},{""id"":9821,""name"":""Copyright"",""value"":""2018""},{""id"":9822,""name"":""Authors"",""value"":""Antonia Clare, Frances Eales, JJ Wilson, Steve Oakes""},{""id"":9823,""name"":""Shipping required"",""value"":""NO""},{""id"":9824,""name"":""Subscription Length"",""value"":""12 Months""},{""id"":12374,""name"":""( "",""value"":"" )""}]"
```

(or)

JSON:
```json

```

## Code Example
```javascript
// Please include a simple example to replicate the issue
//logic to write JSON to CSV line by line
let fields = ['productID','sku','customFields'];
let json2csvCallback = function (err, csv) {
    if (err) throw err;
    console.log(csv);
    return csv;
};

const write = async (fileName, fields, data) => {
    // output file in the same folder
    const filename = path.join(__dirname, 'files', `${fileName}`);
    let rows;
    let options = {
        delimiter : {
            wrap  : '', // Double Quote (") character
            field : ',', // Comma field delimiter
            eol   : '\n' // Newline delimiter
        },
        prependHeader    : true,
        sortHeader       : false,
        excelBOM         : true,
        trimHeaderValues : true,
        trimFieldValues  : true,
        expandArrayObjects: true,
        keys             : fields
    };
    // If file doesn't exist, we will create new file and add rows with headers.    
    if (!fs.existsSync(filename)) {
        rows = await converter.json2csvAsync(data, json2csvCallback, options);
    } else {
        // Rows without headers.
        options['prependHeader'] = false;
        options['trimHeaderValues'] = false;
        console.log("row without header options - ",options);
        rows = await converter.json2csvAsync(data, json2csvCallback, options);
    }

    // Append file function can create new file too.
    fs.appendFileSync(filename, rows);
    // Always add new line if file already exists.
    fs.appendFileSync(filename, "\r\n");
    return filename;
}


```

**Comment by mrodrig** [comment]
Hi @subinpaulneo, thanks for reporting this. I haven't had much time to look at the issue you're reporting, but I should be able to get to it tomorrow after work.

**Comment by mrodrig** [comment]
Thanks for your patience @subinpaulneo. It looks like the issue might be because the `json2csvAsync` function doesn't take a callback, so your code is passing the callback function in the `options` argument's place. When I removed the `json2csvCallback`, the code started honoring the `prependHeader: false` option value correctly:

```
        rows = await converter.json2csvAsync(data, options);
```

Being honest, I was surprised to see your report that it wasn't honoring that option since there are tests ensuring that option is being honored, so I'm glad to see it's a simple fix. 🙂

One other thing I noticed is that you may want to match the `options.delimiter.eol` value with the string you're passing to the  second `fs.appendFileSync` call that you're using to append a newline at the end. Depending on what your use case is, the `\r` might cause issues downstream since it's another character that might get parsed as being part of one of the CSV fields.

![image](https://user-images.githubusercontent.com/2199972/225504351-2e0fb10c-7b7c-4f96-9e49-365d0529b4dc.png)

Hope this helps and feel free to let me know if you run into any other issues!
