### ISSUE TITLE
Field in CSV it turned into an object unexpectedly. 

### ISSUE THREAD

**Issue by hydrohiester** [mrodrig/json-2-csv#254]
## Background Information
- Module Version: ` 5.5.0`
- Node/Browser Version: `20.10.0 `

The issue I'm reporting is with:
- [ ] json2csv
- [X ] csv2json

I have...
- [ X] searched to see if an issue has already been reported.
- [ X ] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [X] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior

CSV Header: 'Account No.'
CSV Field: '01-1800-00'

I expect to get: 
{'Account No.': '01-1800-00'}

## Actual Behavior

It gets converted to 
{ 'Account No': { '': '01-1800-00' }}

If I remove the period in "Account No." it works correctly. Is a period not allowed in a heading? 

I tried setting `excelBOM` to true, but it didn't make a difference.

**Comment by mrodrig** [comment]
Hi @hydrohiester, thanks for reporting this. That definitely sounds like a bug to me. My guess is the parsing logic needs an update to account for that possibility, since it's completely valid.

I'm currently traveling with no access to my typical development machine, but should hopefully be able to take a closer look at this either later this weekend or early next week. I'll keep you posted.

**Comment by mrodrig** [comment]
Thanks again for reporting this @hydrohiester. It ended up being a different issue with the logic in my `doc-path` package rather than what I expected, but it should be resolved now in version `5.5.1` that I just published.
