### ISSUE TITLE
CSV adds unnecessary header column when there is a schema difference

### ISSUE THREAD

**Issue by velmurugaiyan** [mrodrig/json-2-csv#71]
When we convert JSON to CSV and if there is a schema difference in the json, then the module adds unnecessary header and the row containing full values is copied twice.

For Eg, I have used the below json and tried to convert it to csv

[
    {
        Make: 'Nissan',
        Model: 'Murano',
        Year: '2013',
        Specifications:null
    },
    {
        Make: 'BMW',
        Model: 'X5',
        Year: '2014',
        Specifications: {
            Mileage: '3287',
            Trim: 'M'
        }
    }
]

It outputs the below CSV
Make,Model,Year,Specifications,Specifications.Mileage,Specifications.Trim
Nissan,Murano,2013,,,
BMW,X5,2014,3287,M,3287,M

**Comment by mrodrig** [comment]
Sorry for the delayed response. This is happening because of how the module enumerates all possible header fields. When it finds that `Specifications` has a null value for one, it adds it to the list of header fields.  When the data conversion portion goes and actually grabs the value, it's finding `Specifications` to be an object for the second document, so it performs a `JSON.stringify(...)`.  I believe setting a wrap delimiter should fix this since it will put the stringified JSON inside of quotes.

Example:

``` javascript
var options = {
    delimiter : {
        wrap  : '"' // Double Quote (") character
    }
}
```

Then the CSV should appear like this:

```csv
"Make","Model","Year","Specifications","Specifications.Mileage","Specifications.Trim"
"Nissan","Murano","2013","","",""
"BMW","X5","2014","3287,M","3287","M"
```

I haven't tested that just yet, but will try to test it out in a little bit.  I've been meaning to finally push #55 out which will prevent these sorts of things from happening, but haven't been able to fully test to ensure it won't break existing code.

**Comment by mrodrig** [comment]
If you are still encountering this issue, please comment. I'm going to close it out for now though. Thanks!
