### ISSUE TITLE
How to generate a .csv file that uses UTF-8 character encoding

### ISSUE THREAD

**Issue by robin-chilliapple** [mrodrig/json-2-csv#78]
The issue is when I generating a csv file and open it in Microsift Excel, It's showing blank bracket instead of emojis. For Exampale : 

Actual String:
1) 😸 To: You, From: Us ... Happy Thursday ...
2) 💃 You'll be dancing in the street with these hot items!

But in upper string it's not showing smilies. It's showing Square brackets. For reference see attached image. 

![screenshot from 2017-10-10 18-24-15](https://user-images.githubusercontent.com/17025274/31387535-6e6785e8-ade8-11e7-8d03-bcf35a9ffddb.png)

Please provide me some solution, I am stuck on this.
Thanks

**Comment by mrodrig** [comment]
Hi @robin-chilliapple.  Thanks for letting me know about that.  I created an example which would output those two strings with the emojis, and it appears as though the module is handling them correctly.

<img width="773" alt="screen shot 2017-10-10 at 9 21 52 am" src="https://user-images.githubusercontent.com/2199972/31390164-2157edca-ada1-11e7-9cc3-e0ba2cca6879.png">

I think the issue that you're running into might be how Microsoft Excel is encoding/displaying the CSV once it is opened.  I found a link which appears to have instructions on how to open the CSV with UTF-8 encoding so that the emojis will appear.  Unfortunately, the instructions are for Excel 2007, so I'm sure some of the names/options may have changed since.  Here's the link: https://www.itg.ias.edu/content/how-import-csv-file-uses-utf-8-character-encoding-0

**Comment by mrodrig** [comment]
I just tried the instructions in Excel 2016 as well and found they still worked.  Basically you'll want to open Excel 2016, click on the `Data` tab, then click `From Text/CSV`.  From there, select the file that you want to open, and then change the `File Origin` drop-down to `65001: Unicode (UTF-8)`.  Once that has been changed, Excel will open the file with the emojis in it.  Hope this helps!
